openapi: 3.0.0
info:
  title: "TrailService REST API"
  description: "An API for managing trails and related information"
  version: "1.0.0"

servers:
  - url: "/api/v1"

paths:
  /trails:
    get:
      summary: "Get all trails with pagination and sorting"
      operationId: trails.read_all_trails
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
            minimum: 1
          description: "Page number"
        - in: query
          name: per_page
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: "Number of trails per page (maximum 100)"
        - in: query
          name: sort_by
          schema:
            type: string
          description: "Field to sort by"
        - in: query
          name: sort_order
          schema:
            type: string
            enum: [asc, desc]
            default: "asc"
          description: "Sort order"
      responses:
        "200":
          description: "A paginated and sorted list of trails"
          content:
            application/json:
              schema:
                type: object
                properties:
                  TotalTrails:
                    type: integer
                  TotalPages:
                    type: integer
                  CurrentPage:
                    type: integer
                  PerPage:
                    type: integer
                  Trails:
                    type: array
                    items:
                      $ref: "#/components/schemas/Trail"
        "400":
          description: "Invalid pagination or sorting parameters"
    post:
      summary: "Create a new trail"
      operationId: trails.create_trail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Credentials:
                  type: object
                  properties:
                    Email:
                      type: string
                    Password:
                      type: string
                  required:
                    - Email
                    - Password
                Trail:
                  $ref: "#/components/schemas/Trail"
              required:
                - Credentials
                - Trail
      responses:
        "201":
          description: "Trail created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
        "400":
          description: "Invalid input data"
        "403":
          description: "Forbidden - You do not have permission to create this trail"

  /trails/{trail_name}:
    get:
      summary: "Get a trail by name"
      operationId: trails.read_trail_by_name
      parameters:
        - in: "path"
          name: "trail_name"
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Trail retrieved successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
        "404":
          description: "Trail not found"
    put:
      summary: "Update a trail by name"
      operationId: trails.update_trail
      parameters:
        - in: "path"
          name: "trail_name"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Credentials:
                  type: object
                  properties:
                    Email:
                      type: string
                    Password:
                      type: string
                  required:
                    - Email
                    - Password
                Trail:
                  $ref: "#/components/schemas/TrailUpdate"
              required:
                - Credentials
                - Trail
      responses:
        "200":
          description: "Trail updated successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
        "400":
          description: "Invalid input data"
        "403":
          description: "Forbidden - You do not have permission to update this trail"
        "404":
          description: "Trail not found"
    delete:
      summary: "Delete a trail by name"
      operationId: trails.delete_trail
      parameters:
        - in: "path"
          name: "trail_name"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Credentials:
                  type: object
                  properties:
                    Email:
                      type: string
                    Password:
                      type: string
                  required:
                    - Email
                    - Password
      responses:
        "204":
          description: "Trail deleted successfully"
        "403":
          description: "Forbidden - You do not have permission to delete this trail"
        "404":
          description: "Trail not found"

components:
  schemas:
    Location:
      type: object
      properties:
        City:
          type: string
        County:
          type: string
        Country:
          type: string
      required:
        - County
        - Country

    Point:
      type: object
      properties:
        Latitude:
          type: number
          format: float
        Longitude:
          type: number
          format: float
        Description:
          type: string
      required:
        - Latitude
        - Longitude

    Tag:
      type: object
      properties:
        Name:
          type: string
      required:
        - Name

    Trail:
      type: object
      properties:
        CompletionTime:
          type: integer
        Description:
          type: string
        Difficulty:
          type: string
        ElevationGain:
          type: integer
        Length:
          type: number
          format: float
        Name:
          type: string
        Rating:
          type: number
          format: float
        RouteType:
          type: string
        Location:
          $ref: "#/components/schemas/Location"
        Points:
          type: array
          items:
            $ref: "#/components/schemas/Point"
        Tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
      required:
        - Difficulty
        - ElevationGain
        - Length
        - Name
        - Rating
        - RouteType
        - Location
        - Points

    TrailUpdate:
      type: object
      properties:
        CompletionTime:
          type: integer
        Description:
          type: string
        Difficulty:
          type: string
        ElevationGain:
          type: integer
        Length:
          type: number
          format: float
        Name:
          type: string
        Rating:
          type: number
          format: float
        RouteType:
          type: string
        Location:
          $ref: "#/components/schemas/Location"
        Points:
          type: array
          items:
            $ref: "#/components/schemas/Point"
        Tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
