openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API for managing trails and related information"
  version: "1.0.0"

servers:
  - url: "/api/v1"

paths:
  /trails:
    get:
      summary: "Get all trails"
      operationId: trails.read_all_trails
      responses:
        "200":
          description: "A list of trails"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trail'
    post:
      summary: "Create a new trail"
      operationId: trails.create_trail
      requestBody:
        description: "Trail object that needs to be added"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trail'
      responses:
        "201":
          description: "Trail created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trail'

components:
  schemas:
    Location:
      type: object
      properties:
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
    Trail:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        location:
          $ref: '#/components/schemas/Location'
    Point:
      type: object
      properties:
        Latitude:
          type: number
          format: float
        Longitude:
          type: number
          format: float
        Description:
          type: string
      required:
        - Latitude
        - Longitude

    Tag:
      type: object
      properties:
        Name:
          type: string
      required:
        - Name

    Trail:
      type: object
      properties:
        UserId:
          type: integer
        Name:
          type: string
        Difficulty:
          type: string
        Rating:
          type: number
          format: float
        Length:
          type: number
          format: float
        ElevationGain:
          type: integer
        RouteType:
          type: string
        CompletionTime:
          type: integer
        Description:
          type: string
        Points:
          type: array
          items:
            $ref: "#/components/schemas/Point"
        Tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
        Location:
          $ref: "#/components/schemas/Location"
