openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API for managing trails and related information"
  version: "1.0.0"

servers:
  - url: "/api/v1"

paths:
  /trails:
    get:
      summary: "Get all trails"
      operationId: trails.read_all_trails
      responses:
        "200":
          description: "A list of trails"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Trail"
    post:
      summary: "Create a new trail"
      operationId: trails.create_trail
      requestBody:
        description: "Trail object that needs to be added"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trail"
      responses:
        "201":
          description: "Trail created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
    put:
      summary: "Update a trail by name"
      operationId: trails.update_trail
      parameters:
        - in: "path"
          name: "trail_name"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Credentials:
                  type: object
                  properties:
                    Email:
                      type: string
                    Password:
                      type: string
                  required:
                    - Email
                    - Password
                Trail:
                  $ref: "#/components/schemas/TrailUpdate"
              required:
                - Credentials
                - Trail
      responses:
        "200":
          description: "Trail updated successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"

components:
  schemas:
    Location:
      type: object
      properties:
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
    Trail:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        location:
          $ref: "#/components/schemas/Location"
    Point:
      type: object
      properties:
        Latitude:
          type: number
          format: float
        Longitude:
          type: number
          format: float
        Description:
          type: string
      required:
        - Latitude
        - Longitude
    Tag:
      type: object
      properties:
        Name:
          type: string
      required:
        - Name
